version: "3.7"

services:
    reddit_checker:
        command: nodemon --watch './*.go' --watch 'config.json' --signal SIGTERM --exec 'go' run .
        depends_on:
            - elasticsearch
            - kibana
        build:
            context: .
            target: DEV
        container_name: reddit_checker
        volumes:
            - ./:/src
    filebeat:
        image: docker.elastic.co/beats/filebeat:8.1.3
        depends_on:
            - elasticsearch
        volumes:
            - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
            - ./logs/:/logs/

    logstash:
        image: docker.elastic.co/logstash/logstash:8.1.3
        volumes:
            - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
        depends_on:
            - elasticsearch

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
        healthcheck:
            test: [ "CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health" ]
            interval: 3s
            timeout: 3s
            retries: 80
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
            - 9300:9300

    kibana:
        image: docker.elastic.co/kibana/kibana:8.1.3
        depends_on:
            - elasticsearch
        healthcheck:
            test: [ "CMD", "curl", "-s", "-f", "http://localhost:5601/api/status" ]
            interval: 3s
            timeout: 3s
            retries: 80
        ports:
            - 5601:5601

volumes:
    elasticsearch-data:
        driver: local